config/routes.rb
Phpstepdown::Application.routes.draw do
  
  resources :locations

  match '/sessions/gate', to: 'sessions#gate', via: [:get, :post], as: 'gate'
  
  match '/reasonsbyfacilityreport', to: 'discharges#reasonsbyfacilityreport', via: [:get, :post]
  match '/datadumpreport', to: 'discharges#datadumpreport', via: [:get, :post]
  match '/mordata', to: 'discharges#mordata', via: [:get, :post]
  
  get '/sessions/destroy' => "sessions#destroy", :as => 'logout'
  
  get '/locations/hide/:id' => "locations#hide", :as => 'hide_location'
  get '/locations/unhide/:id' => "locations#unhide", :as => 'unhide_location'
  
  get '/dropreasons/hide/:id' => "dropreasons#hide", :as => 'hide_dropreason'
  get '/dropreasons/unhide/:id' => "dropreasons#unhide", :as => 'unhide_dropreason'
  
  get '/discharges/hide/:id' => "discharges#hide", :as => 'hide_discharge'
  get '/discharges/unhide/:id' => "discharges#unhide", :as => 'unhide_discharge'

  resources :discharges

  resources :dropreasons

   root :to => 'discharges#index'

end

app/models/discharge.rb
class Discharge < ActiveRecord::Base
  belongs_to :location
  belongs_to :dropreason
  
  validates_presence_of :facility_id
  validates_presence_of :medikid
  validates_uniqueness_of :medikid
  validates :ipdays, :numericality => {:only_integer => true}
  validates :phpvisits, :numericality => {:only_integer => true }

  attr_accessible :active, :dropreason_id, :ipdays, :otherdetail, :phpvisits, :facility_id, :medikid, :ishidden, 
                  :ipdischargedate, :phpdischargedate, :phpstartdate, :gender
  
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names 
      all.each do |discharge|
        csv << discharge.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.ipDayOptions
    ipDayOptionArray=[]
    ipDayOptionArray << ["0-was not IP patient", 0]
    (1..11).each do |day|
      ipDayOptionArray<<[day,day]
    end
    ipDayOptionArray << ["12+", 12]
    ipDayOptionArray
  end
  
  def self.phpVisitOptions
    phpVisitOptionArray=[]
    phpVisitOptionArray << ["0-dropped out before starting PHP", 0]
    (1..10).each do |day|
      phpVisitOptionArray << [day, day]
    end
    phpVisitOptionArray << [">10", 11]
    phpVisitOptionArray
  end
  
  def self.phpVisitCodeLookup(codenum)

    codeArray=Discharge.phpVisitOptions
    codeArray.each do |elem|
      return elem[0] if elem[1]==codenum
    end
  end
  
  def self.locFilterWhere(locfilter=-999)
    if locfilter==-999
      return "facility_id is not null"
    else
      return "facility_id=#{locfilter}"
    end
  end
  
  
  def self.activePatients(locfilter=-999)
    Discharge.where(active: true, ishidden: false).where(Discharge.locFilterWhere(locfilter)).order("phpstartdate desc")
  end
  
  def self.droppedOutPatients(locfilter=-999)
    Discharge.where(active: false, ishidden: false, phpvisits: 0).where(Discharge.locFilterWhere(locfilter)).order("ipdischargedate desc")
  end
  
  def self.dischargedPatients(locfilter=-999)
    Discharge.where("active='f' and ishidden='f' and phpvisits>0").where(Discharge.locFilterWhere(locfilter)).order("phpdischargedate desc")
  end
  
  def modIpDischargeDate
    modDate=self.ipdischargedate.strftime("%m-%d-%Y") unless self.ipdischargedate.nil?
    modDate="n/a" if self.ipdays==0 || self.ipdischargedate.nil?
    modDate
  end

  def modPhpStartDate
    modDate=self.phpstartdate.strftime("%m-%d-%Y") unless self.phpstartdate.nil?
    modDate="n/a" if self.phpstartdate.nil?
    modDate
  end

  
  def modPhpDischargeDate
    modDate=self.phpdischargedate.strftime("%m-%d-%Y")
    modDate="n/a-no dropped out w/o starting PHP" if self.phpvisits==0
    modDate
  end
  
  def self.reasonCount(reason_id=nil, location_id=nil, period=nil, patienttype=nil)
  
   #filtercriteria applicable to all queries here
   filterCrit="ishidden='f' and active='f'"  
    
   #create where criteria for type (default to drop outs)
   pattypeCrit="phpvisits=0 and ipdays>0"
   pattypeCrit="phpvisits>0" if patienttype=="discharges"


   #otherwise set date as first day of selected month
   period=Date.new(period.split('-')[1].to_i, period.split('-')[0].to_i,1) unless period.nil?

   #set period to current month if nil
   period=Date.today if period.nil?

   
   #create where criteria for period
   #default to drop out case (use ip discharge date to determine period range)
   periodCrit={:ipdischargedate=>period.beginning_of_month..period.end_of_month} 
   periodCrit={:phpdischargedate=>period.beginning_of_month..period.end_of_month} if patienttype=="discharges"
   
    
   reasonCrit="dropreason_id is not null"
   reasonCrit="dropreason_id=#{reason_id}" unless reason_id.nil?
   
   locationCrit="facility_id is not null"
   locationCrit="facility_id=#{location_id}" unless location_id.nil?
   
   Discharge.where(filterCrit).where(pattypeCrit).where(periodCrit).where(reasonCrit).where(locationCrit).count
  
  end
  
  def self.reasonCountLocPct(r_id=nil, loc_id=nil, per=nil, ptype=nil)
    numerator=Discharge.reasonCount(r_id, loc_id, per, ptype)
    denominator=Discharge.reasonCount(nil, loc_id, per, ptype)
    
    if denominator>0
      return (100*(numerator.to_f/denominator.to_f)).to_i.to_s+"%"
    else
      return ""
    end
    
  end
  
  #class method to return "red" or "green" or "white" based on whether reason over/underindexes versus average
  def self.extValIndex(r_id, loc_id, per, ptype)
    unless Discharge.reasonCount(r_id, nil, per, ptype)==0 || Discharge.reasonCount(nil, loc_id, per, ptype)==0
      totalPct=Discharge.reasonCount(r_id, nil, per,ptype).to_f/Discharge.reasonCount(nil, nil,per,ptype).to_f
      facilityPct=Discharge.reasonCount(r_id, loc_id, per, ptype).to_f/Discharge.reasonCount(nil, loc_id,per,ptype).to_f
      if facilityPct<totalPct*0.80
        "red"
      else
        if facilityPct>totalPct*1.20
          "green"
        else
          "white"
        end
      end
    else
      "white"
    end
  end
  
  
  def self.reportingPeriods
    timePeriods={}
    #reporting period start: April 2014
    mytime=Time.utc(2014,"apr",1,0,1,1)
    loop do
      timePeriods[mytime.strftime("%b-%Y")]=mytime.strftime("%m-%Y")
      mytime=mytime.months_since(1)
      break if mytime>Time.now
    end
    timePeriods
     
  end
  
  def self.morMonthRange
    months=[]
    startDate=Date.new(2013,1,1)
    myDate=startDate
    loop do 
      months<<myDate
      myDate=myDate.months_since(1)
      break if myDate>Date.today
    end
    months
  end
  
 def self.ipDischarges(tperiod, loc_id)

   #filtercriteria applicable to all queries here
   filterCrit="ishidden='f' and ipdays>0"  
   periodCrit={:ipdischargedate=>tperiod.beginning_of_month..tperiod.end_of_month} 
   locCrit="facility_id=#{loc_id}"
   Discharge.where(filterCrit).where(periodCrit).where(locCrit)

 end

 def self.ipDischargesCount(tperiod, loc_id)
   Discharge.ipDischarges(tperiod, loc_id).count
 end
 
 def self.phpStepdown(tperiod, loc_id)
   Discharge.ipDischarges(tperiod, loc_id).where("active='t' or phpvisits>0")
 end
 
 def self.phpStepdownCount(tperiod, loc_id)
   Discharge.phpStepdown(tperiod, loc_id).count
 end
 
 def self.phpDropouts(tperiod, loc_id)
   Discharge.ipDischarges(tperiod, loc_id).where("active='f' and phpvisits=0")
 end
 
 def self.phpDropoutCount(tperiod, loc_id)
   Discharge.phpDropouts(tperiod, loc_id).count
 end

 def self.phpDropoutWithReasonCount(reason_id, tperiod, loc_id)
   Discharge.phpDropouts(tperiod, loc_id).where("dropreason_id=#{reason_id}").count
 end
 
 def self.nVisDschrgCt(numVisit, loc_id, tperiod)
   filterCrit="ishidden='f' and active='f' and phpvisits=#{numVisit}"
   locCrit="facility_id=#{loc_id}"
   periodCrit={:phpdischargedate=>tperiod.beginning_of_month..tperiod.end_of_month}
   Discharge.where(filterCrit).where(locCrit).where(periodCrit).count
 end
 
 
 def self.stepdownIpRangeCt(range, loc_id, tperiod)
   Discharge.phpStepdown(tperiod, loc_id).where(ipdays: (range[0]..range[1])).count
 end
 
  def self.dropoutIpRangeCt(range, loc_id, tperiod)
    Discharge.phpDropouts(tperiod, loc_id).where(ipdays: (range[0]..range[1])).count
  end
  
  def self.genderOptions
    genderOptionArray=[["Female", "F"], ["Male", "M"]]
    genderOptionArray
  end
  
  
end

app/controllers/discharges_controller.rb
class DischargesController < ApplicationController
  
  layout "main"
  # GET /discharges
  # GET /discharges.json
  def index
    @curpg = :discharges
    @discharges = Discharge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discharges }
      format.csv { render text: @discharges.to_csv }
    end
  end

  # GET /discharges/1
  # GET /discharges/1.json
  def show
    @curpg = :discharges
    @discharge = Discharge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discharge }
    end
  end

  # GET /discharges/new
  # GET /discharges/new.json
  def new
    @curpg = :discharges
    @discharge = Discharge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discharge }
    end
  end

  # GET /discharges/1/edit
  def edit
    @curpg = :discharges
    @discharge = Discharge.find(params[:id])
  end

  # POST /discharges
  # POST /discharges.json
  def create
    @curpg = :discharges
    @discharge = Discharge.new(params[:discharge])

    respond_to do |format|
      if @discharge.save
        format.html { redirect_to :controller => "discharges", :action => "index" }
        format.json { render json: @discharge, status: :created, location: @discharge }
      else
        format.html { render action: "new" }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discharges/1
  # PUT /discharges/1.json
  def update
    @curpg = :discharges
    @discharge = Discharge.find(params[:id])

    respond_to do |format|
      if @discharge.update_attributes(params[:discharge])
        format.html { redirect_to :controller => "discharges", :action => "index"}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discharge.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def hide
    @discharge = Discharge.find(params[:id])
    @discharge.update_attributes(:ishidden=>true)
    redirect_to :action => "index"
  end
  
  def unhide
    @discharge = Discharge.find(params[:id])
    @discharge.update_attributes(:ishidden=>false)
    redirect_to :action => "index"
  end
  
  def reasonsbyfacilityreport
    @curpg = :reports
    @period=Date.today.strftime("%m-%Y") 
    @period=params[:yrmonth] unless params[:yrmonth].nil?
    @pattype=params[:patienttype]
    
    periodstring=Date.new(@period.split('-')[1].to_i, @period.split('-')[0].to_i,1).strftime("%B-%Y")
    
    pattypelabel="Patients Not Stepping Down To PHP (#{periodstring})"
    pattypelabel="Patients Leaving PHP after Starting PHP (#{periodstring})" if @pattype=="discharges"
  
    @countLabel="Count of "+pattypelabel
    @pctLabel="Percent of "+pattypelabel
  end
  
  def mordata
    @curpg = :reports
    @loc=1
    @loc=params[:locfilter] unless params[:locfilter].nil?
  end
  
  def datadumpreport
  end

  # DELETE /discharges/1
  # DELETE /discharges/1.json
  def destroy
  #  @discharge = Discharge.find(params[:id])
  #  @discharge.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to discharges_url }
  #    format.json { head :no_content }
  #  end
  end
end

app/helpers/discharges_helper.rb
module DischargesHelper
end

app/views/discharges/_form.html.erb
<%= form_for @discharge, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @discharge.errors.any? %>
  <div class="alert alert-danger">
  	<%= pluralize(@discharge.errors.count, "error") %> prohibited patient information from being saved:<br>
	<ul>
		<% @discharge.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
  </div>
  <% end %>

  <div class="form-group">
    <label for="medikid" class="col-sm-4 control-label">Patient Medik ID</label>
    <div class="col-sm-8">
	 <%= f.text_field :medikid, :class => 'form-control' %>
    </div>
  </div>  
  
  <div class="form-group">
    <label for="gender" class="col-sm-4 control-label">Patient Gender</label>
    <div class="col-sm-8">
	 <%= f.select(:gender, Discharge.genderOptions, {},  {:class => 'form-control', :id=>'gender'}) %>
    </div>
  </div>  

  <div class="form-group">
    <label for="ipdays" class="col-sm-4 control-label">Inpatient Days</label>
    <div class="col-sm-3">
	  <%= f.select(:ipdays, Discharge.ipDayOptions, {},  {:class => 'form-control', :id=>'ipdays'}) %>
    </div>
	<div class="col-sm-5"></div>
  </div>  
  
  <div class="form-group hidden" id="ipdateformgroup">
    <label for="ipdischargedate" class="col-sm-4 control-label">IP Discharge Date</label>
    <div class="col-sm-8">
	  <%= f.date_select :ipdischargedate, {:order => [:month, :day, :year]}, {}   %>
    </div>
  </div>
  
  <div class="form-group hidden" id="phpstartdateformgroup">
    <label for="phpstartdate" class="col-sm-4 control-label">PHP Start Date</label>
    <div class="col-sm-4">
	  <%= f.date_select :phpstartdate, {:order => [:month, :day, :year]}, {}   %>
    </div>
	<div class="col-sm-4">
	</div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-4 control-label">Inpatient Facility</label>
    <div class="col-sm-3">
		<%= f.select(:facility_id, Location.unhiddenLocations(session[:locfilter]), {}, {:class=> 'form-control', :id=>'facility_id'})%>
    </div>
	<div class="col-sm-5"></div>
  </div>
  <div class="form-group">
    <label for="active" class="col-sm-4 control-label">Still in PHP Program @ Springstone </label>
    <div class="col-sm-3">
      <%= f.select(:active, [['Yes', 'true'], ['No', 'false']], {},  {:class => 'form-control', :id=>'active'}) %>
    </div>
	<div class="col-sm-5"></div>
  </div>
  <div id="dropoffonlyinputs" class="hidden">
	  <div class="form-group">
	   <label for="phpvisits" class="col-sm-4 control-label">PHP Visits </label>
	    <div class="col-sm-8">
		  <%= f.select(:phpvisits, Discharge.phpVisitOptions, {},  {:class => 'form-control', :id=>'phpvisits'}) %>
	    </div>
	  </div>
	  <div class="form-group hidden" id="phpenddateformgroup">
	   <label for="phpdropdate" class="col-sm-4 control-label">PHP Drop Out Date </label>
	    <div class="col-sm-8">
		  <%= f.date_select :phpdischargedate, {:order => [:month, :day, :year]}, {}   %>
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="dropreason" class="col-sm-4 control-label">Reason For Declining/Leaving PHP</label>
	    <div class="col-sm-8">
	      <%= f.select(:dropreason_id, Dropreason.unhiddenReasons, {}, {:class=> 'form-control', :id=>'dropreason_id'})%>
	    </div>
	  </div>
	  <div class="form-group hidden" id="otherdetailgroup">
	    <label for="otherdetail" class="col-sm-4 control-label">Please Describe Reason: </label>
	    <div class="col-sm-8">
	      <%= f.text_field :otherdetail, :class => 'form-control' %>
	    </div>
	  </div>
  </div>
  
  <div class="form-group">
   <label for="phpvisits" class="col-sm-4 control-label"></label>
    <div class="col-sm-8">
      <button class="btn btn-primary">Save Patient</button>
	  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            discharges_path, :class => 'btn btn-default' %>
    </div>
  </div>
  
 
<% end %>

app/views/discharges/datadumpreport.html.erb
<p>Data Dump</p>

app/views/discharges/edit.html.erb
<%- model_class = Discharge -%>
<div class="page-header">
  <h1>Edit Patient Information</h1>
</div>
<%= render :partial => 'form' %>

app/views/discharges/index.html.erb
<%- model_class = Discharge -%>


  <h2>Active PHP Patients</h2>
  <div class="alert alert-success">The patients in the list below are still in our PHP program.  Please review this list daily and (1) fill out discharge information for any patients who have left PHP. (2) Add new information for any patients who have started PHP treatment.  </div>
  
  
<table class="table table-striped">
  <thead>
    <tr>
	  <th>Medik ID</th>
	  <th>Gender</th>
      <th>Inpatient Days</th>
      <th>Facility </th>
      <th>PHP Start Date</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% Discharge.activePatients(session[:locfilter]).each do |discharge| %>
    <% #Discharge.where(active: true, ishidden: false).order("created_at desc").each do |discharge| %>
      <tr>
		<td><%= discharge.medikid %></td>
		<td><%= discharge.gender %></td>
        <td><%= discharge.ipdays %></td>
        <td>
			<%= Location.find(discharge.facility_id).name %>
		</td>
        <td>
			<%= discharge.modPhpStartDate %>
		</td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_discharge_path(discharge), :class => 'btn btn-default btn-xs' %>
		  <% if discharge.ishidden==true %>
		  	<%= link_to "Unhide", unhide_discharge_path(discharge.id), 
			:id=>"noshading", :class => 'btn btn-danger btn-xs'  %>
		  <% else %>
		  	<%= link_to "Hide", hide_discharge_path(discharge.id), 
			:id=> "noshading", :class => 'btn btn-danger btn-xs'  %>
		  <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  <a id="noshading" class="btn btn-success" href="<%= new_discharge_path %>">Add New Patient</a>


<br><br>

<h2>Patients Not Stepping Down to PHP</h2>

  <div class="alert alert-success">
	  The patients in the list below have left IP treatment without starting PHP at Springstone.  Please review this list monthly for accuracy.  
  </div>
  
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
  	  	<th>Medik ID</th>
	  	<th>Gender</th>
        <th>IP Days</th>
        <th>Reason Dropped</th>
        <th>Facility </th>
        <th>IP Discharge Date</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
  	  <% Discharge.droppedOutPatients(session[:locfilter]).each do |discharge| %>
      <% #Discharge.where(active: false, ishidden: false).order("phpdischargedate desc").each do |discharge| %>
        <tr>
          <td><%= link_to discharge.id, discharge_path(discharge) %></td>
  		<td><%= discharge.medikid %></td>
		<td><%= discharge.gender %></td>
          <td><%= discharge.ipdays %></td>
          <td><%= Dropreason.find(discharge.dropreason_id).name %></td>
          <td>
  			<%= Location.find(discharge.facility_id).name %>
  		</td>
          <td><%= discharge.modIpDischargeDate %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_discharge_path(discharge), :class => 'btn btn-default btn-xs' %>
  		  <% if discharge.ishidden==true %>
  		  	<%= link_to "Unhide", unhide_discharge_path(discharge.id), 
  				:id=> "noshading", :class => 'btn btn-danger btn-xs'  %>
  		  <% else %>
  		  	<%= link_to "Hide", hide_discharge_path(discharge.id), 
  			:id=>"noshading", :class => 'btn  btn-danger btn-xs'  %>
  		  <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <a id="noshading" class="btn btn-success" href="<%= new_discharge_path %>">Add New Patient</a>


<br><br>

<h2>Discharged PHP Patients</h2>
  <div class="alert alert-success">The patients in the list below have left our PHP program.  Please review this list monthly for accuracy. </div>



<table class="table table-striped">
  <thead>
    <tr>
	  <th>Medik ID</th>
	  <th>Gender</th>
      <th>IP Days</th>
      <th># PHP Visits</th>
      <th>Reason Left PHP</th>
      <th>Facility </th>
      <th>PHP Discharge Date</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
	  <% Discharge.dischargedPatients(session[:locfilter]).each do |discharge| %>
    <% #Discharge.where(active: false, ishidden: false).order("phpdischargedate desc").each do |discharge| %>
      <tr>
		<td><%= discharge.medikid %></td>
		<td><%= discharge.gender %></td>
        <td><%= discharge.ipdays %></td>
        <td><%= Discharge.phpVisitCodeLookup(discharge.phpvisits) %></td>
        <td><%= Dropreason.find(discharge.dropreason_id).name %></td>
        <td>
			<%= Location.find(discharge.facility_id).name %>
		</td>
        <td><%= discharge.modPhpDischargeDate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_discharge_path(discharge), :class => 'btn btn-default btn-xs' %>
		  <% if discharge.ishidden==true %>
		  	<%= link_to "Unhide", unhide_discharge_path(discharge.id), 
				:id=> "noshading", :class => 'btn btn-danger btn-xs'  %>
		  <% else %>
		  	<%= link_to "Hide", hide_discharge_path(discharge.id), 
			:id=>"noshading", :class => 'btn  btn-danger btn-xs'  %>
		  <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>
<h2>Hidden Patients</h2>
  <div class="alert alert-success">The patients in the list below were hidden/dropped from the active or discharge lists above.  These hidden patients will not show up in any reporting.  Click the unhide button to restore any of these patients to the active or discharged lists. </div>



<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
	  <th>Medik ID</th>
	  <th>Gender</th>
      <th>Inpatient Days</th>
      <th># PHP Visits</th>
      <th>Reason Dropped/Left PHP</th>
      <th>Facility </th>
      <th>Date Created</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% Discharge.where(ishidden: true).order("created_at desc").each do |discharge| %>
      <tr>
        <td><%= link_to discharge.id, discharge_path(discharge) %></td>
		<td><%= discharge.medikid %></td>
		<td><%= discharge.gender %></td>
        <td><%= discharge.ipdays %></td>
        <td>n/a-unhide to show</td>
        <td>n/a-unhide to show</td>
        <td>
			<%= Location.find(discharge.facility_id).name %>
		</td>
        <td><%= discharge.created_at.strftime("%m-%d-%Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_discharge_path(discharge), :class => 'btn btn-default btn-xs' %>
		  <% if discharge.ishidden==true %>
		  	<%= link_to "Unhide", unhide_discharge_path(discharge.id), :class => 'btn btn-danger btn-xs'  %>
		  <% else %>
		  	<%= link_to "Hide", hide_discharge_path(discharge.id), :class => 'btn btn-danger btn-xs'  %>
		  <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/discharges/new.html.erb
<%- model_class = Discharge -%>
<div class="page-header">
  <h1>Add Patient Record</h1>
</div>
<%= render :partial => 'form' %>

app/views/discharges/show.html.erb
<%- model_class = Discharge -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ipdays) %>:</strong></dt>
  <dd><%= @discharge.ipdays %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @discharge.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phpvisits) %>:</strong></dt>
  <dd><%= @discharge.phpvisits %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dropreason_id) %>:</strong></dt>
  <dd><%= @discharge.dropreason_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:otherdetail) %>:</strong></dt>
  <dd><%= @discharge.otherdetail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facility_id) %>:</strong></dt>
  <dd><%= @discharge.facility_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              discharges_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_discharge_path(@discharge), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              discharge_path(@discharge),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>