config/routes.rb
Phpstepdown::Application.routes.draw do
  
  resources :locations

  match '/sessions/gate', to: 'sessions#gate', via: [:get, :post], as: 'gate'
  
  match '/reasonsbyfacilityreport', to: 'discharges#reasonsbyfacilityreport', via: [:get, :post]
  match '/datadumpreport', to: 'discharges#datadumpreport', via: [:get, :post]
  match '/mordata', to: 'discharges#mordata', via: [:get, :post]
  
  get '/sessions/destroy' => "sessions#destroy", :as => 'logout'
  
  get '/locations/hide/:id' => "locations#hide", :as => 'hide_location'
  get '/locations/unhide/:id' => "locations#unhide", :as => 'unhide_location'
  
  get '/dropreasons/hide/:id' => "dropreasons#hide", :as => 'hide_dropreason'
  get '/dropreasons/unhide/:id' => "dropreasons#unhide", :as => 'unhide_dropreason'
  
  get '/discharges/hide/:id' => "discharges#hide", :as => 'hide_discharge'
  get '/discharges/unhide/:id' => "discharges#unhide", :as => 'unhide_discharge'

  resources :discharges

  resources :dropreasons

   root :to => 'discharges#index'

end

app/models/dropreason.rb
class Dropreason < ActiveRecord::Base
  attr_accessible :name, :ishidden
  
  validates_uniqueness_of :name 
  validates_presence_of :name 
  
  def self.unhiddenReasons
    reasonList=[]
    Dropreason.order("name asc").where(:ishidden=>false).each do |reason|
      reasonList << [reason.name, reason.id]
    end
    reasonList
  end
  
  def self.orderedUnhiddenReasons
    Dropreason.where(ishidden: false).order("name asc")
  end
  
end

app/controllers/dropreasons_controller.rb
class DropreasonsController < ApplicationController
  # GET /dropreasons
  # GET /dropreasons.json
  def index
    @curpg = :admintools
    @dropreasons = Dropreason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dropreasons }
    end
  end

  # GET /dropreasons/1
  # GET /dropreasons/1.json
  def show
    @curpg = :admintools
    @dropreason = Dropreason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dropreason }
    end
  end

  # GET /dropreasons/new
  # GET /dropreasons/new.json
  def new
    @curpg = :admintools
    @dropreason = Dropreason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dropreason }
    end
  end

  # GET /dropreasons/1/edit
  def edit
    @curpg = :admintools
    @dropreason = Dropreason.find(params[:id])
  end

  # POST /dropreasons
  # POST /dropreasons.json
  def create
    @curpg = :admintools
    @dropreason = Dropreason.new(params[:dropreason])

    respond_to do |format|
      if @dropreason.save
        format.html { redirect_to :action => "index" }
        format.json { render json: @dropreason, status: :created, location: @dropreason }
      else
        format.html { render action: "new" }
        format.json { render json: @dropreason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dropreasons/1
  # PUT /dropreasons/1.json
  def update
    @curpg = :admintools
    @dropreason = Dropreason.find(params[:id])

    respond_to do |format|
      if @dropreason.update_attributes(params[:dropreason])
        format.html { redirect_to :action => "index" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dropreason.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def hide
    @curpg = :admintools
    @dropreason = Dropreason.find(params[:id])
    @dropreason.update_attributes(:ishidden=>true)
    redirect_to :controller => "dropreasons", :action => "index"
  end
  
  def unhide
    @curpg = :admintools
    @dropreason = Dropreason.find(params[:id])
    @dropreason.update_attributes(:ishidden=>false)
    redirect_to :controller => "dropreasons", :action => "index"
  end

  # DELETE /dropreasons/1
  # DELETE /dropreasons/1.json
  def destroy
 #   @dropreason = Dropreason.find(params[:id])
 #   @dropreason.destroy
 #
 #   respond_to do |format|
 #     format.html { redirect_to dropreasons_url }
 #    format.json { head :no_content }
 #   end
  end
end

app/helpers/dropreasons_helper.rb
module DropreasonsHelper
end

app/views/dropreasons/_form.html.erb
<%= form_for @dropreason, :html => { :class => 'form-horizontal' } do |f| %>


  <div class="form-group">
    <label for="name" class="col-sm-4 control-label">Reason Description</label>
    <div class="col-sm-8">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>  
  
  <div class="form-group">
	<label for="name" class="col-sm-4 control-label"></label>
	<div class="col-sm-8">
		 <input class="btn btn-primary" type="submit" value="Create" name="commit">
	</div>
  </div>
  
  <div class="form-group">
	<label for="name" class="col-sm-4 control-label"></label>
	<div class="col-sm-8">
	     <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	               dropreasons_path, :class => 'btn btn-default' %>
	</div>
  </div>
 

 
<% end %>

app/views/dropreasons/edit.html.erb
<h1>Editing dropreason</h1>

<%= render 'form' %>

<%= link_to 'Show', @dropreason %> |
<%= link_to 'Back', dropreasons_path %>

app/views/dropreasons/index.html.erb
<%- model_class = Dropreason -%>
<div class="page-header">
  <h1>PHP Drop Out Reasons</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
	   <th>Hidden (Y/N)</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @dropreasons.each do |dropreason| %>
      <tr>
        <td><%= link_to dropreason.id, dropreason_path(dropreason) %></td>
        <td><%= dropreason.name %></td>
		<td><%= dropreason.ishidden.to_s.convert_to_yn %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_dropreason_path(dropreason), :class => 'btn btn-default btn-xs' %>
		  <% if dropreason.ishidden==true %>
		  	<%= link_to "Unhide", unhide_dropreason_path(dropreason.id), :class => 'btn btn-danger btn-xs'  %>
		  <% else %>
		  	<%= link_to "Hide", hide_dropreason_path(dropreason.id), :class => 'btn btn-danger btn-xs'  %>
		  <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_dropreason_path,
            :class => 'btn btn-primary' %>

app/views/dropreasons/new.html.erb
<%- model_class = Dropreason -%>
<div class="page-header">
	<h1>New Reason for PHP Drop Out</h1>
</div>
<%= render :partial => 'form' %>

app/views/dropreasons/show.html.erb
<%- model_class = Dropreason -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @dropreason.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              dropreasons_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dropreason_path(@dropreason), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dropreason_path(@dropreason),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>