config/routes.rb
Phpstepdown::Application.routes.draw do
  
  resources :locations

  match '/sessions/gate', to: 'sessions#gate', via: [:get, :post], as: 'gate'
  
  match '/reasonsbyfacilityreport', to: 'discharges#reasonsbyfacilityreport', via: [:get, :post]
  match '/datadumpreport', to: 'discharges#datadumpreport', via: [:get, :post]
  match '/mordata', to: 'discharges#mordata', via: [:get, :post]
  
  get '/sessions/destroy' => "sessions#destroy", :as => 'logout'
  
  get '/locations/hide/:id' => "locations#hide", :as => 'hide_location'
  get '/locations/unhide/:id' => "locations#unhide", :as => 'unhide_location'
  
  get '/dropreasons/hide/:id' => "dropreasons#hide", :as => 'hide_dropreason'
  get '/dropreasons/unhide/:id' => "dropreasons#unhide", :as => 'unhide_dropreason'
  
  get '/discharges/hide/:id' => "discharges#hide", :as => 'hide_discharge'
  get '/discharges/unhide/:id' => "discharges#unhide", :as => 'unhide_discharge'

  resources :discharges

  resources :dropreasons

   root :to => 'discharges#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :ishidden
  
  def self.unhiddenLocations(locfilter=-999)
    locationList=[]
    Location.order("name asc").where(:ishidden=>false).where(Location.filterWhere(locfilter)).each do |location|
      locationList << [location.name, location.id]
    end
    locationList
  end
  
  def self.unhiddenLocHsh
    locationList={}
    Location.unhiddenLocations(-999).each do |loc|
      locationList[loc[0]]=loc[1]
    end
    locationList
  end
  
  def self.unhiddenLocationsWithAll
    locationList=Location.unhiddenLocations
    locationList.unshift(["All", -999])
    locationList
  end
  
  def self.filterWhere(locfilter=-999)
    if locfilter==-999
      return "id is not null"
    else
      return "id=#{locfilter}"
    end
  end
  
  def self.orderedUnhiddenLocations
    Location.where(ishidden: false).order("name asc")
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  
  before_filter :check_admin, :except => :index
  
  def check_admin
    if session[:adminpassword].present? 
      unless session[:adminpassword].nil?
        if Digest::SHA2.hexdigest(session[:adminpassword].to_s)==ENV['ADMIN_PASS_HASH'].to_s
        else
          redirect_to gate_path 
        end
      else
        redirect_to gate_path
      end
    else
      redirect_to gate_path
    end
  end
  
  def index
    @locations = Location.all
    @curpg = :admintools
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @curpg = :admintools
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @curpg = :admintools
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @curpg = :admintools
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @curpg = :admintools
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to :controller => "locations", :action => "index"  }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @curpg = :admintools
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to :controller => "locations", :action => "index" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def hide
    @curpg = :admintools
    @location = Location.find(params[:id])
    @location.update_attributes(:ishidden=>true)
    redirect_to :controller => "locations", :action => "index"
  end
  
  def unhide
    @curpg = :admintools
    @location = Location.find(params[:id])
    @location.update_attributes(:ishidden=>false)
    redirect_to :controller => "locations", :action => "index"
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  #should not be able to destroy locations, only hide them from view
  def destroy
#    @location = Location.find(params[:id])
#    @location.update_attributes(:ishidden => true)
#
#    respond_to do |format|
#      format.html { redirect_to locations_url }
#      format.json { head :no_content }
#    end
    
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for @location, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <label for="name" class="col-sm-4 control-label">Facility Name</label>
   	<div class="col-sm-8">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  
  <div class="form-group">
	<label for="name" class="col-sm-4 control-label"></label>
	<div class="col-sm-8">
		 <%= f.submit nil, :class => 'btn btn-primary' %>
	</div>
  </div>
  
  
  <div class="form-group">
	<label for="name" class="col-sm-4 control-label"></label>
	<div class="col-sm-8">
	     <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	               locations_path, :class => 'btn btn-default' %>
	</div>
  </div>
  
  
<% end %>

app/views/locations/edit.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Hidden (Y/N)</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.id, location_path(location) %></td>
        <td><%= location.name %></td>
        <td><%= location.ishidden.to_s.convert_to_yn %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-default btn-xs' %>
					  
		  <% if location.ishidden==true %>
		  	<%= link_to "Unhide", unhide_location_path(location.id), :class => 'btn btn-danger btn-xs'  %>
		  <% else %>
		  	<%= link_to "Hide", hide_location_path(location.id), :class => 'btn btn-danger btn-xs'  %>
		  <% end %>
		  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1>New Facility</h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @location.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ishidden) %>:</strong></dt>
  <dd><%= @location.ishidden %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              locations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_location_path(@location), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              location_path(@location),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>